<?php

		// Exit if accessed directly
		if ( ! defined( 'ABSPATH' ) ) {
			exit;
		}

		function fusion_builder_add_photography_demo( $demos ) {

		$demos['photography'] = array (
  'category' => 'Avada Photography',
  'pages' => 
  array (
     
    array (
      'name' => 'About Me',
      'link' => 'https://avada.website/photography/about-me/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="40px" padding_bottom="3%" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" margin_bottom_small="20px" padding_right_small="20px" padding_left_small="20px" min_height="" link=""][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" content_align="center" size="3" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky"]BORN TO SHOOT THE WORLD AROUND ME[/fusion_title][fusion_text content_alignment="center"]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="var(--awb-color8)" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="160px" padding_bottom="100px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_top_medium="80px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" margin_bottom="65px" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" min_height="" link=""][fusion_imageframe lightbox="no" style_type="none" hover_type="none" bordercolor="hsla(var(--awb-color1-h),var(--awb-color1-s),var(--awb-color1-l),calc( var(--awb-color1-a) - 80% ))" borderradius="4px" align="none" linktarget="_self" animation_type="0" animation_direction="down" animation_speed="0.1" hide_on_mobile="no"] <img src="https://placehold.it/1170x451" alt="" />[/fusion_imageframe][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="false" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="9%" padding_bottom="0%" padding_left="9%" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" spacing_right="2%" min_height="" link=""][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" content_align="left" size="3" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky"]Always Searching For The Shot[/fusion_title][fusion_text]Aliquam interdum neque non quam scelerisque efficitur. Ut sagittis, mi sed vestibulum bibendum, lacus lacus vulputate enim, vel posuere diam nibh sit amet velit. Vivamus pulvinar sit amet enim sed sagittis. Ut quis porttitor lacus. Nulla tris cursus. Pellentesque molis velit eu bidum.[/fusion_text][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_right="9%" padding_left="9%" animation_type="0" animation_direction="down" animation_speed="0.1" animation_offset="top-into-view" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_left="2%" align_content="flex-start" margin_bottom_medium="15px" min_height="" link=""][fusion_progress percentage="88" striped="no" animated_stripes="no"]Landscapes[/fusion_progress][fusion_progress percentage="93" striped="no" animated_stripes="no"]Wildlife[/fusion_progress][fusion_progress percentage="98" striped="no" animated_stripes="no"]Business[/fusion_progress][fusion_progress percentage="84" striped="no" animated_stripes="no"]Lifestyle[/fusion_progress][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_image="https://placehold.it/2000x1287" background_parallax="up" enable_mobile="no" parallax_speed="0.4" background_repeat="no-repeat" background_position="center center" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="180px" padding_bottom="140px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_top_medium="100px" padding_bottom_medium="40px" padding_top_small="80px" padding_bottom_small="20px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" min_height="" link=""][fusion_testimonials design="clean" backgroundcolor="transparent" textcolor="hsla(var(--awb-color5-h),var(--awb-color5-s),calc( var(--awb-color5-l) + 63% ),var(--awb-color5-a))"][fusion_testimonial name="ANSEL ADAMS" avatar="none" target="_self"]"When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence."[/fusion_testimonial][fusion_testimonial name="ERNST HASS" avatar="none" target="_self"]"There is only you and your camera. The limitations in your photography are in yourself, for what we see is what we are."[/fusion_testimonial][fusion_testimonial name="ROBERT FRANK" avatar="none" target="_self"]"Black and white are the colors of photography. They symbolize the alternatives of hope and despair to which mankind is subjected."[/fusion_testimonial][/fusion_testimonials][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="var(--awb-color8)" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="160px" padding_bottom="40px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_top_medium="100px" padding_bottom_medium="0px" padding_top_small="80px" padding_bottom_small="10px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="8%" padding_bottom="0%" padding_left="8%" margin_bottom="65px" animation_type="0" animation_direction="down" animation_speed="1" animation_offset="top-into-view" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" margin_bottom_medium="20px" margin_bottom_small="0px" min_height="" link=""][fusion_post_cards post_card="1151" post_card_list_view="0" source="posts" post_type="post" posts_by="all" custom_field_comparison="exists" out_of_stock="include" show_hidden="no" filters="no" number_posts="0" offset="0" orderby="date" orderby_custom_field_type="CHAR" orderby_term="name" order="DESC" upcoming_events_only="yes" featured_events_only="no" scrolling="pagination" hide_on_mobile="small-visibility,medium-visibility,large-visibility" layout="carousel" filters_height="36" filters_alignment_medium="flex-start" filters_alignment_small="flex-start" filters_alignment="flex-start" active_filter_border_size="3" flex_align_items="flex-start" columns_medium="0" columns_small="0" columns="2" column_spacing="84" row_spacing="144" separator_style_type="none" separator_alignment="center" separator_border_size="1" autoplay="no" loop="yes" scroll_items="1" mouse_scroll="yes" mouse_pointer="custom" cursor_color_mode="auto" show_nav="dots" dots_position="below" dots_spacing="8" dots_align="center" dots_size="8" dots_active_size="8" slider_animation="fade" animation_direction="left" animation_speed="0.3" animation_delay="0" dots_margin_top="24px" dots_active_color="var(--awb-color3)" dots_color="var(--awb-color5)" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="100" padding_bottom="0" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" margin_bottom="0px" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" min_height="" link=""][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" content_align="center" size="3" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky"]
<p>CLIENTS I\'VE WORKED WITH</p>
[/fusion_title][fusion_images picture_size="auto" hover_type="none" autoplay="yes" columns="5" column_spacing="30" scroll_items="1" show_nav="no" mouse_scroll="yes" border="no" lightbox="no"][fusion_image linktarget="_self" image="https://placehold.it/270x160" /][fusion_image linktarget="_self" image="https://placehold.it/270x160" /][fusion_image linktarget="_self" image="https://placehold.it/270x160" /][fusion_image linktarget="_self" image="https://placehold.it/270x160" /][fusion_image linktarget="_self" image="https://placehold.it/270x160" /][fusion_image linktarget="_self" image="https://placehold.it/270x160" /][/fusion_images][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-about-me',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_portfolio_category' => 'a:1:{i:0;s:1:"0";}',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-about-me',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'Collections',
      'link' => 'https://avada.website/photography/collections/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" margin_top_medium="80px" admin_toggled="no"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_image="https://placehold.it/1170x300" background_repeat="no-repeat" background_position="center top" hover_type="none" border_position="all" border_style="solid" padding_top="100px" padding_right="0px" padding_bottom="100px" padding_left="0px" margin_bottom="0px" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" padding_bottom_medium="80px" padding_top_small="30px" min_height="" link=""][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" content_align="center" size="4" font_size="16px" line_height="var(--awb-typography2-line-height)" letter_spacing="0.4em" text_color="hsla(var(--awb-color3-h),var(--awb-color3-s),calc(var(--awb-color3-l) + 54%),var(--awb-color3-a))" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" fusion_font_variant_title_font="var(--awb-typography2)" fusion_font_family_title_font="var(--awb-typography2-font-family)" text_transform="var(--awb-typography2-text-transform)"]
<p>FRESH WORKS FROM AROUND THE WORLD</p>
[/fusion_title][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" content_align="center" size="1" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" font_size="50px" letter_spacing="0.15em"]
<p>THE AVADA COLLECTION</p>
[/fusion_title][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_bottom="100px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_bottom_medium="60px" padding_bottom_small="76px" admin_toggled="yes"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" min_height="" link=""][fusion_post_cards post_card="1152" post_card_list_view="0" source="posts" post_type="avada_portfolio" posts_by="all" custom_field_comparison="exists" out_of_stock="include" show_hidden="no" filters="no" number_posts="0" offset="0" orderby="date" orderby_custom_field_type="CHAR" orderby_term="name" order="DESC" upcoming_events_only="yes" featured_events_only="no" scrolling="infinite" hide_on_mobile="small-visibility,medium-visibility,large-visibility" layout="grid" filters_height="36" filters_alignment_medium="flex-start" filters_alignment_small="flex-start" filters_alignment="flex-start" active_filter_border_size="3" flex_align_items="stretch" columns_medium="0" columns_small="0" columns="2" column_spacing="36" row_spacing="36" separator_style_type="none" separator_alignment="center" separator_border_size="1" autoplay="no" loop="yes" scroll_items="0" mouse_scroll="no" mouse_pointer="default" cursor_color_mode="auto" show_nav="yes" dots_position="bottom" dots_spacing="4" dots_align="center" dots_size="8" dots_active_size="8" slider_animation="fade" animation_direction="left" animation_speed="0.3" animation_delay="0" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_image="https://placehold.it/2000x938" background_parallax="up" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="center bottom" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="120px" padding_bottom="80px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_bottom_small="20px" padding_top_small="80px" admin_toggled="yes"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" min_height="" link=""][fusion_testimonials design="clean" backgroundcolor="transparent" textcolor="hsla(var(--awb-color5-h),var(--awb-color5-s),calc( var(--awb-color5-l) + 63% ),var(--awb-color5-a))"][fusion_testimonial name="ANSEL ADAMS" avatar="none" target="_self"]"When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence." [/fusion_testimonial][fusion_testimonial name="ERNST HASS" avatar="none" target="_self"]"There is only you and your camera. The limitations in your photography are in yourself, for what we see is what we are." [/fusion_testimonial][fusion_testimonial name="ROBERT FRANK" avatar="none" target="_self"]"Black and white are the colors of photography. They symbolize the alternatives of hope and despair to which mankind is subjected." [/fusion_testimonial][/fusion_testimonials][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => '',
        'pyre_slider_position' => 'default',
        'pyre_slider_type' => 'no',
        'pyre_slider' => '0',
        'pyre_wooslider' => '0',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_fallback' => '',
        'pyre_avada_rev_styles' => 'default',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg' => '',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg' => '',
        'pyre_page_bg_color' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg' => 'https://placehold.it/2340x1200',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'no-repeat',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_page_title' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
      ),
    ),
     
    array (
      'name' => 'Hire Me',
      'link' => 'https://avada.website/photography/hire-me/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="20px" padding_bottom="80px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" flex_justify_content="center" padding_right_medium="8%" padding_left_medium="8%" padding_top_small="50px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="10%" padding_bottom="0%" padding_left="10%" margin_bottom="30px" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" padding_left_medium="20px" padding_right_medium="20px" margin_bottom_medium="30px" min_height="" link=""][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" content_align="center" size="3" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky"]LOOKING FOR BEAUTIFUL IMAGES THAT CAPTURE THE OCCASION?[/fusion_title][fusion_text]
<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliqui.</p>
[/fusion_text][/fusion_builder_column][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="false" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" margin_bottom="1px" animation_type="0" animation_direction="down" animation_speed="0.1" element_content="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" spacing_right="2%" min_height="" link=""][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="false" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" margin_bottom="0" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_right="2%" spacing_left="2%" min_height="" link=""][fusion_form form_post_id="1040" hide_on_mobile="small-visibility,medium-visibility,large-visibility" /][/fusion_builder_column][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="true" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" margin_bottom="1px" animation_type="0" animation_direction="down" animation_speed="0.1" element_content="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_left="2%" min_height="" link=""][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container hundred_percent="yes" equal_height_columns="no" hide_on_mobile="no" background_color="var(--awb-color7)" background_position="left top" background_repeat="no-repeat" fade="no" background_parallax="none" enable_mobile="no" parallax_speed="0.3" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" border_style="solid" padding_top="80px" padding_right="4%" padding_bottom="100px" padding_left="4%" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" flex_justify_content="center" padding_bottom_small="70px"][fusion_builder_row][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="false" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" animation_type="0" animation_direction="down" animation_speed="0.1" element_content="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" spacing_right="2%" min_height="" link=""][/fusion_builder_column][fusion_builder_column type="1_2" type="1_2" layout="1_2" last="false" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_right="2%" spacing_left="2%" min_height="" link=""][fusion_title size="3" content_align="center" style_type="single solid"]MORE FROM THE AVADA COLLECTION[/fusion_title][/fusion_builder_column][fusion_builder_column type="1_4" type="1_4" layout="1_4" last="true" spacing="yes" center_content="no" hide_on_mobile="large-visibility" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" animation_type="0" animation_direction="down" animation_speed="0.1" element_content="" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="false" spacing_left="2%" min_height="" link=""][/fusion_builder_column][fusion_builder_column type="1_1" type="1_1" layout="1_1" background_position="left top" border_style="solid" spacing="yes" background_repeat="no-repeat" margin_top="0px" margin_bottom="0px" animation_speed="0.3" animation_direction="left" hide_on_mobile="no" center_content="no" min_height="none" last="true" hover_type="none" border_position="all" align_self="flex-start" first="true" link=""][fusion_post_cards post_card="1152" post_card_list_view="0" source="posts" acf_repeater_field="" acf_relationship_field="" post_type="avada_portfolio" posts_by="all" custom_field_name="" custom_field_comparison="exists" custom_field_value="" out_of_stock="include" show_hidden="no" filters="no" number_posts="5" offset="0" orderby="date" orderby_custom_field_name="" orderby_custom_field_type="CHAR" orderby_term="name" order="DESC" upcoming_events_only="yes" featured_events_only="no" scrolling="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" layout="grid" filters_height="36" filters_alignment_medium="flex-start" filters_alignment_small="flex-start" filters_alignment="flex-start" active_filter_border_size="3" flex_align_items="stretch" columns_medium="0" columns_small="0" columns="5" column_spacing="40" row_spacing="40" separator_style_type="none" separator_alignment="center" separator_border_size="1" autoplay="no" loop="yes" scroll_items="0" mouse_scroll="no" mouse_pointer="default" cursor_color_mode="auto" show_nav="yes" arrow_box="" arrow_position="" dots_position="bottom" dots_spacing="4" dots_align="center" dots_size="8" dots_active_size="8" slider_animation="fade" animation_direction="left" animation_color="" animation_speed="0.3" animation_delay="0" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-hire-me',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-hire-me',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'On Location',
      'link' => 'https://avada.website/photography/on-location/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="50px" padding_bottom="20px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_top_small="30px" padding_bottom_small="0px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="12%" padding_bottom="0%" padding_left="12%" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" padding_right_medium="6%" padding_left_medium="6%" padding_right_small="20px" padding_left_small="20px" margin_bottom_small="0px" min_height="" link=""][fusion_post_cards post_card="1151" post_card_list_view="0" source="posts" acf_repeater_field="" acf_relationship_field="" post_type="post" posts_by="all" custom_field_name="" custom_field_comparison="exists" custom_field_value="" out_of_stock="include" show_hidden="no" filters="no" number_posts="0" offset="0" orderby="date" orderby_custom_field_name="" orderby_custom_field_type="CHAR" orderby_term="name" order="DESC" upcoming_events_only="yes" featured_events_only="no" scrolling="pagination" hide_on_mobile="small-visibility,medium-visibility,large-visibility" layout="grid" filters_height="36" filters_alignment_medium="flex-start" filters_alignment_small="flex-start" filters_alignment="flex-start" active_filter_border_size="3" flex_align_items="flex-start" columns_medium="0" columns_small="0" columns="1" column_spacing="40" row_spacing="144" separator_style_type="none" separator_alignment="center" separator_border_size="1" autoplay="no" loop="yes" scroll_items="0" mouse_scroll="no" mouse_pointer="default" cursor_color_mode="auto" show_nav="yes" arrow_box="" arrow_position="" dots_position="bottom" dots_spacing="4" dots_align="center" dots_size="8" dots_active_size="8" slider_animation="fade" animation_direction="left" animation_color="" animation_speed="0.3" animation_delay="0" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_color="var(--awb-color7)" background_image="https://placehold.it/2000x938" background_parallax="up" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="center center" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="100px" padding_bottom="40px" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex" padding_top_small="70px" padding_bottom_small="10px"][fusion_builder_row][fusion_builder_column type="1_1" type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" min_height="" link=""][fusion_title size="3" content_align="center" style_type="none" margin_bottom="36px"]SUBSCRIBE TO FOLLOW US ON LOCATION[/fusion_title][fusion_form form_post_id="1044" hide_on_mobile="small-visibility,medium-visibility,large-visibility" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-on-location',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-on-location',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '0px',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
     
    array (
      'name' => 'Photography Home',
      'link' => 'https://avada.website/photography/',
      'page_template' => '100-width.php',
      'content' => '[fusion_builder_container type="flex" hundred_percent="no" hundred_percent_height="min" hundred_percent_height_scroll="no" align_content="center" flex_align_items="flex-start" flex_justify_content="flex-start" hundred_percent_height_center_content="yes" equal_height_columns="no" container_tag="div" hide_on_mobile="small-visibility,medium-visibility,large-visibility" status="published" border_style="solid" box_shadow="no" box_shadow_blur="0" box_shadow_spread="0" gradient_start_position="0" gradient_end_position="100" gradient_type="linear" radial_direction="center center" linear_angle="180" background_position="center center" background_repeat="no-repeat" fade="no" background_parallax="fixed" enable_mobile="no" parallax_speed="0.3" background_blend_mode="none" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" absolute="off" absolute_devices="small,medium,large" sticky="off" sticky_devices="small-visibility,medium-visibility,large-visibility" sticky_transition_offset="0" scroll_offset="0" animation_direction="left" animation_speed="0.3" filter_hue="0" filter_saturation="100" filter_brightness="100" filter_contrast="100" filter_invert="0" filter_sepia="0" filter_opacity="100" filter_blur="0" filter_hue_hover="0" filter_saturation_hover="100" filter_brightness_hover="100" filter_contrast_hover="100" filter_invert_hover="0" filter_sepia_hover="0" filter_opacity_hover="100" filter_blur_hover="0" background_image="https://placehold.it/1522x1008" padding_top="6vw" padding_bottom="6vw" min_height="100vh" render_logics="W3sib3BlcmF0b3IiOiJhbmQiLCJjb21wYXJpc29uIjoibm90LWVxdWFsIiwiZmllbGQiOiJkZXZpY2VfdHlwZSIsInZhbHVlIjoibW9iaWxlIn1d" skip_lazy_load="skip"][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" align_self="auto" content_layout="column" align_content="center" valign_content="flex-start" content_wrap="wrap" center_content="no" target="_self" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" order_medium="0" order_small="0" hover_type="none" border_style="solid" box_shadow="no" box_shadow_blur="0" box_shadow_spread="0" background_type="single" gradient_start_position="0" gradient_end_position="100" gradient_type="linear" radial_direction="center center" linear_angle="180" background_position="left top" background_repeat="no-repeat" background_blend_mode="none" filter_type="regular" filter_hue="0" filter_saturation="100" filter_brightness="100" filter_contrast="100" filter_invert="0" filter_sepia="0" filter_opacity="100" filter_blur="0" filter_hue_hover="0" filter_saturation_hover="100" filter_brightness_hover="100" filter_contrast_hover="100" filter_invert_hover="0" filter_sepia_hover="0" filter_opacity_hover="100" filter_blur_hover="0" animation_type="fade" animation_direction="up" animation_speed="0.8" last="true" border_position="all" first="true" min_height="" link=""][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" title_link="off" link_target="_self" content_align="center" size="2" text_shadow="no" text_shadow_blur="0" style_type="none" sep_color="var(--awb-color1)" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" margin_bottom="0" margin_top="0" fusion_font_variant_title_font="var(--awb-typography2)" fusion_font_family_title_font="var(--awb-typography2-font-family)" font_size="var(--awb-typography2-font-size)" line_height="var(--awb-typography2-line-height)" letter_spacing="var(--awb-typography2-letter-spacing)" text_transform="var(--awb-typography2-text-transform)"]— WE TAKE THE TIME TO —[/fusion_title][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" title_link="off" link_target="_self" content_align="center" size="1" font_size="var(--awb-custom_typography_1-font-size)" line_height="var(--awb-custom_typography_1-line-height)" text_shadow="no" text_shadow_blur="0" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" fusion_font_family_title_font="var(--awb-custom_typography_1-font-family)" fusion_font_variant_title_font="var(--awb-custom_typography_1)" letter_spacing="var(--awb-custom_typography_1-letter-spacing)" text_transform="var(--awb-custom_typography_1-text-transform)"]STAND &amp; STARE[/fusion_title][fusion_button link="https://1.envato.market/o9WW9" target="_self" alignment="center" color="custom" button_gradient_top_color="hsla(var(--awb-color1-h),var(--awb-color1-s),var(--awb-color1-l),calc(var(--awb-color1-a) - 100%))" button_gradient_bottom_color="hsla(var(--awb-color1-h),var(--awb-color1-s),var(--awb-color1-l),calc(var(--awb-color1-a) - 100%))" button_gradient_top_color_hover="hsla(var(--awb-color1-h),var(--awb-color1-s),var(--awb-color1-l),calc(var(--awb-color1-a) - 100%))" button_gradient_bottom_color_hover="hsla(var(--awb-color1-h),var(--awb-color1-s),var(--awb-color1-l),calc(var(--awb-color1-a) - 100%))" accent_hover_color="var(--awb-color1)" border_hover_color="var(--awb-color1)" size="large" stretch="no" icon_position="left" icon_divider="no" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" margin_left="10px" border_top="1px" border_right="1px" border_bottom="1px" border_left="1px"]BE INSPIRED[/fusion_button][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container type="flex" hundred_percent="yes" hundred_percent_height="no" hundred_percent_height_scroll="no" align_content="stretch" flex_align_items="flex-start" flex_justify_content="flex-start" hundred_percent_height_center_content="yes" equal_height_columns="no" container_tag="div" hide_on_mobile="small-visibility,medium-visibility,large-visibility" status="published" border_style="solid" box_shadow="no" box_shadow_blur="0" box_shadow_spread="0" gradient_start_position="0" gradient_end_position="100" gradient_type="linear" radial_direction="center center" linear_angle="180" background_position="center center" background_repeat="no-repeat" fade="no" background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_blend_mode="none" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" absolute="off" absolute_devices="small,medium,large" sticky="off" sticky_devices="small-visibility,medium-visibility,large-visibility" sticky_transition_offset="0" scroll_offset="0" animation_direction="left" animation_speed="0.3" filter_hue="0" filter_saturation="100" filter_brightness="100" filter_contrast="100" filter_invert="0" filter_sepia="0" filter_opacity="100" filter_blur="0" filter_hue_hover="0" filter_saturation_hover="100" filter_brightness_hover="100" filter_contrast_hover="100" filter_invert_hover="0" filter_sepia_hover="0" filter_opacity_hover="100" filter_blur_hover="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" render_logics="W3sib3BlcmF0b3IiOiJhbmQiLCJjb21wYXJpc29uIjoiZXF1YWwiLCJmaWVsZCI6ImRldmljZV90eXBlIiwidmFsdWUiOiJtb2JpbGUifV0="][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" align_self="auto" content_layout="column" align_content="flex-start" valign_content="flex-start" content_wrap="wrap" center_content="no" target="_self" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" order_medium="0" order_small="0" margin_bottom="0px" hover_type="none" border_style="solid" box_shadow="no" box_shadow_blur="0" box_shadow_spread="0" background_type="single" gradient_start_position="0" gradient_end_position="100" gradient_type="linear" radial_direction="center center" linear_angle="180" background_position="left top" background_repeat="no-repeat" background_blend_mode="none" filter_type="regular" filter_hue="0" filter_saturation="100" filter_brightness="100" filter_contrast="100" filter_invert="0" filter_sepia="0" filter_opacity="100" filter_blur="0" filter_hue_hover="0" filter_saturation_hover="100" filter_brightness_hover="100" filter_contrast_hover="100" filter_invert_hover="0" filter_sepia_hover="0" filter_opacity_hover="100" filter_blur_hover="0" animation_direction="left" animation_speed="0.3" last="true" border_position="all" first="true" min_height="" link=""][fusion_imageframe image_id="1087|full" skip_lazy_load="skip" hover_type="none" align_medium="none" align_small="none" align="none" lightbox="no" linktarget="_self" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" filter_hue="0" filter_saturation="100" filter_brightness="100" filter_contrast="100" filter_invert="0" filter_sepia="0" filter_opacity="100" filter_blur="0" filter_hue_hover="0" filter_saturation_hover="100" filter_brightness_hover="100" filter_contrast_hover="100" filter_invert_hover="0" filter_sepia_hover="0" filter_opacity_hover="100" filter_blur_hover="0"]https://placehold.it/1398x666[/fusion_imageframe][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container type="flex" hundred_percent="no" hundred_percent_height="no" hundred_percent_height_scroll="no" align_content="center" flex_align_items="flex-start" flex_justify_content="flex-start" hundred_percent_height_center_content="yes" equal_height_columns="no" container_tag="div" hide_on_mobile="small-visibility,medium-visibility,large-visibility" status="published" border_style="solid" box_shadow="no" box_shadow_blur="0" box_shadow_spread="0" gradient_start_position="0" gradient_end_position="100" gradient_type="linear" radial_direction="center center" linear_angle="180" background_position="center center" background_repeat="no-repeat" fade="no" background_parallax="fixed" enable_mobile="no" parallax_speed="0.3" background_blend_mode="none" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" absolute="off" absolute_devices="small,medium,large" sticky="off" sticky_devices="small-visibility,medium-visibility,large-visibility" sticky_transition_offset="0" scroll_offset="0" animation_direction="left" animation_speed="0.3" filter_hue="0" filter_saturation="100" filter_brightness="100" filter_contrast="100" filter_invert="0" filter_sepia="0" filter_opacity="100" filter_blur="0" filter_hue_hover="0" filter_saturation_hover="100" filter_brightness_hover="100" filter_contrast_hover="100" filter_invert_hover="0" filter_sepia_hover="0" filter_opacity_hover="100" filter_blur_hover="0" padding_top="60px" padding_bottom="60px" min_height="100vh" render_logics="W3sib3BlcmF0b3IiOiJhbmQiLCJjb21wYXJpc29uIjoiZXF1YWwiLCJmaWVsZCI6ImRldmljZV90eXBlIiwidmFsdWUiOiJtb2JpbGUifV0=" skip_lazy_load="skip" background_color="var(--awb-color1)"][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" align_self="auto" content_layout="column" align_content="center" valign_content="flex-start" content_wrap="wrap" center_content="no" target="_self" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" order_medium="0" order_small="0" hover_type="none" border_style="solid" box_shadow="no" box_shadow_blur="0" box_shadow_spread="0" background_type="single" gradient_start_position="0" gradient_end_position="100" gradient_type="linear" radial_direction="center center" linear_angle="180" background_position="left top" background_repeat="no-repeat" background_blend_mode="none" filter_type="regular" filter_hue="0" filter_saturation="100" filter_brightness="100" filter_contrast="100" filter_invert="0" filter_sepia="0" filter_opacity="100" filter_blur="0" filter_hue_hover="0" filter_saturation_hover="100" filter_brightness_hover="100" filter_contrast_hover="100" filter_invert_hover="0" filter_sepia_hover="0" filter_opacity_hover="100" filter_blur_hover="0" animation_type="fade" animation_direction="up" animation_speed="0.8" last="true" border_position="all" first="true" margin_bottom_medium="0px" min_height="" link=""][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" title_link="off" link_target="_self" content_align="center" size="2" font_size="18px" text_shadow="no" text_shadow_blur="0" text_color="var(--awb-color6)" style_type="none" sep_color="var(--awb-color1)" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" margin_bottom="10px" margin_top="0" fusion_font_variant_title_font="var(--awb-typography2)" fusion_font_family_title_font="var(--awb-typography2-font-family)" line_height="var(--awb-typography2-line-height)" letter_spacing="var(--awb-typography2-letter-spacing)" text_transform="var(--awb-typography2-text-transform)"]— WE TAKE THE TIME TO —[/fusion_title][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" title_link="off" link_target="_self" content_align="center" size="1" font_size="60px" line_height="var(--awb-custom_typography_1-line-height)" text_shadow="no" text_shadow_blur="0" text_color="var(--awb-color6)" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" fusion_font_family_title_font="var(--awb-custom_typography_1-font-family)" fusion_font_variant_title_font="var(--awb-custom_typography_1)" letter_spacing="var(--awb-custom_typography_1-letter-spacing)"]STAND &amp; STARE[/fusion_title][fusion_button link="https://bit.ly/3avzGqi" target="_self" alignment="center" color="default" button_gradient_top_color="rgba(236,72,88,0)" button_gradient_bottom_color="rgba(236,72,88,0)" button_gradient_top_color_hover="rgba(29,30,33,0)" button_gradient_bottom_color_hover="rgba(29,30,33,0)" accent_hover_color="var(--awb-color1)" border_hover_color="var(--awb-color1)" size="large" stretch="no" icon_position="left" icon_divider="no" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky" margin_left="10px" border_top="1px" border_right="1px" border_bottom="1px" border_left="1px"]BE INSPIRED[/fusion_button][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container background_parallax="none" enable_mobile="no" parallax_speed="0.3" background_repeat="no-repeat" background_position="left top" video_aspect_ratio="16:9" video_mute="yes" video_loop="yes" fade="no" border_style="solid" padding_top="120px" padding_bottom="2.5%" hundred_percent="no" equal_height_columns="no" hide_on_mobile="no" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" flex_column_spacing="0px" type="flex"][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" last="true" spacing="yes" center_content="no" hide_on_mobile="no" background_repeat="no-repeat" background_position="left top" hover_type="none" border_position="all" border_style="solid" padding_top="0%" padding_right="15%" padding_bottom="0%" padding_left="15%" animation_type="0" animation_direction="down" animation_speed="0.1" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" first="true" margin_bottom_small="20px" min_height="" link="" background_blend_mode="overlay"][fusion_title title_type="text" rotation_effect="bounceIn" display_time="1200" highlight_effect="circle" loop_animation="off" highlight_width="9" highlight_top_margin="0" content_align="center" size="3" style_type="none" animation_direction="left" animation_speed="0.3" hide_on_mobile="small-visibility,medium-visibility,large-visibility" sticky_display="normal,sticky"]CAPTURING MOMENTS AS THEY HAPPEN[/fusion_title][fusion_text content_alignment="center"]Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container][fusion_builder_container hundred_percent="yes" equal_height_columns="no" hide_on_mobile="no" background_position="left top" background_repeat="no-repeat" fade="no" background_parallax="none" enable_mobile="no" parallax_speed="0.3" video_aspect_ratio="16:9" video_loop="yes" video_mute="yes" border_style="solid" padding_top="0px" padding_right="4%" padding_bottom="100px" padding_left="4%" border_sizes_top="0px" border_sizes_bottom="0px" border_sizes_left="0px" border_sizes_right="0px" type="flex" padding_bottom_small="60px"][fusion_builder_row][fusion_builder_column type="1_1" layout="1_1" background_position="left top" border_style="solid" spacing="yes" background_repeat="no-repeat" margin_top="0px" margin_bottom="0px" animation_speed="0.3" animation_direction="left" hide_on_mobile="no" center_content="no" min_height="none" last="true" hover_type="none" border_position="all" align_self="flex-start" first="true" link="" background_blend_mode="overlay"][fusion_post_cards post_card="1152" post_card_list_view="0" source="posts" post_type="avada_portfolio" posts_by="all" custom_field_comparison="exists" out_of_stock="include" show_hidden="no" filters="no" number_posts="0" offset="0" orderby="date" orderby_custom_field_type="CHAR" orderby_term="name" order="DESC" upcoming_events_only="yes" featured_events_only="no" scrolling="no" hide_on_mobile="small-visibility,medium-visibility,large-visibility" layout="grid" filters_height="36" filters_alignment_medium="flex-start" filters_alignment_small="flex-start" filters_alignment="flex-start" active_filter_border_size="3" flex_align_items="flex-start" columns_medium="0" columns_small="0" columns="4" column_spacing="40" row_spacing="40" separator_style_type="none" separator_alignment="center" separator_border_size="1" autoplay="no" loop="yes" scroll_items="0" mouse_scroll="no" mouse_pointer="default" cursor_color_mode="auto" show_nav="yes" dots_position="bottom" dots_spacing="4" dots_align="center" dots_size="8" dots_active_size="8" slider_animation="fade" animation_direction="left" animation_speed="0.3" animation_delay="0" /][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]',
      'meta' => 
      array (
        'pyre_demo_slider' => 'photography-home',
        'pyre_portfolio_width_100' => 'no',
        'pyre_portfolio_content_length' => 'default',
        'pyre_portfolio_excerpt' => '',
        'pyre_portfolio_filters' => 'yes',
        'pyre_portfolio_text_layout' => 'default',
        'pyre_portfolio_featured_image_size' => 'default',
        'pyre_portfolio_column_spacing' => '',
        'pyre_slider_type' => 'flex',
        'pyre_slider' => '0',
        'pyre_wooslider' => 'photography-home',
        'pyre_revslider' => '0',
        'pyre_elasticslider' => '0',
        'pyre_slider_position' => 'default',
        'pyre_avada_rev_styles' => 'default',
        'pyre_fallback' => '',
        'pyre_main_top_padding' => '',
        'pyre_main_bottom_padding' => '',
        'pyre_hundredp_padding' => '',
        'pyre_show_first_featured_image' => 'no',
        'pyre_display_header' => 'yes',
        'pyre_header_100_width' => 'default',
        'pyre_header_bg_color' => '',
        'pyre_header_bg_opacity' => '',
        'pyre_header_bg' => '',
        'pyre_header_bg_full' => 'no',
        'pyre_header_bg_repeat' => 'repeat',
        'pyre_displayed_menu' => 'default',
        'pyre_display_footer' => 'default',
        'pyre_display_copyright' => 'default',
        'pyre_footer_100_width' => 'default',
        'pyre_sidebar_position' => 'default',
        'pyre_sidebar_bg_color' => '',
        'pyre_page_bg_layout' => 'default',
        'pyre_page_bg_color' => '',
        'pyre_page_bg' => '',
        'pyre_page_bg_full' => 'no',
        'pyre_page_bg_repeat' => 'repeat',
        'pyre_wide_page_bg_color' => '',
        'pyre_wide_page_bg' => '',
        'pyre_wide_page_bg_full' => 'no',
        'pyre_wide_page_bg_repeat' => 'repeat',
        'pyre_page_title' => 'default',
        'pyre_page_title_breadcrumbs_search_bar' => 'default',
        'pyre_page_title_text' => 'default',
        'pyre_page_title_text_alignment' => 'default',
        'pyre_page_title_custom_text' => '',
        'pyre_page_title_text_size' => '',
        'pyre_page_title_custom_subheader' => '',
        'pyre_page_title_custom_subheader_text_size' => '',
        'pyre_page_title_font_color' => '',
        'pyre_page_title_100_width' => 'default',
        'pyre_page_title_height' => '',
        'pyre_page_title_mobile_height' => '',
        'pyre_page_title_bar_bg_color' => '',
        'pyre_page_title_bar_borders_color' => '',
        'pyre_page_title_bar_bg' => '',
        'pyre_page_title_bar_bg_retina' => '',
        'pyre_page_title_bar_bg_full' => 'default',
        'pyre_page_title_bg_parallax' => 'default',
      ),
    ),
  ),
);

			return $demos;
		}
		add_filter( 'fusion_builder_get_demo_pages', 'fusion_builder_add_photography_demo' );